version: "3.7"

services: 
 satdress:
    build: . 
    container_name: satdress
    environment:
      - PORT=18641
      - DOMAIN=webchain3.xyz
      - SECRET=askdbasjdhvakjvsdjasd
      - SITE_OWNER_URL=https://t.me/fiatjaf
      - SITE_OWNER_NAME=@fiatjaf
      - SITE_NAME=Satdress
    ports:
      - 18641:18641
    volumes:
      - satdress-data:/satdress.com

volumes:
  satdress-data:
    name: satdress-data

